global:
  scrape_interval:     15s
  evaluation_interval: 15s

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']
  
  - job_name: 'jenkins'
    scrape_interval: 5s
    metrics_path: /prometheus
    static_configs:
      - targets: ['jenkins:8080']

  - job_name: 'elasticsearch'
    scrape_interval: 10s
    static_configs:
      - targets: ['es-exporter-container:9114']

  - job_name: 'kibana'
    metrics_path: _prometheus/metrics
    scrape_interval: 10s
    static_configs:
      - targets: ['kibana:5601']

  - job_name: 'fluentd'
    scrape_interval: 10s
    static_configs:
      - targets: ['fluentd:24231']

  - job_name: 'nexus'
    scrape_interval: 10s
    metrics_path: /service/metrics/prometheus
    basic_auth:
      username: admin
      password: admin
    static_configs:
      - targets: ['nexus:8081']

  - job_name: 'sonarqube'
    metrics_path: '/api/prometheus/metrics'
    static_configs:
      - targets: ['sonarqube:9000']
